version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"      # Frontend (nginx)
      - "3001:3001"  # Backend API (optional direct access)
      - "5432:5432"  # PostgreSQL (optional direct access)
    environment:
      - NODE_ENV=production
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=teamterrain
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - API_AUTH_TOKEN=your-api-auth-token-change-this
      - PORT=3001
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - app_logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
  app_logs:
