name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build application
        run: bun run build
        env:
          VITE_NODE_ENV: production
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
          VITE_API_AUTH_TOKEN: ${{ secrets.VITE_API_AUTH_TOKEN }}
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_LOCATION_TRACKER_ENDPOINT: ${{ vars.VITE_LOCATION_TRACKER_ENDPOINT }}
          VITE_USERS_ENDPOINT: ${{ vars.VITE_USERS_ENDPOINT }}
          VITE_LOGIN_ENDPOINT: ${{ vars.VITE_LOGIN_ENDPOINT }}
          VITE_APP_NAME: "Employees Map"
          VITE_APP_VERSION: "1.0.0"
          VITE_DEFAULT_MAP_CENTER_LNG: "36.8219"
          VITE_DEFAULT_MAP_CENTER_LAT: "-1.2921"
          VITE_DEFAULT_MAP_ZOOM: "6"
          VITE_MAP_STYLE: "mapbox://styles/mapbox/streets-v12"
          VITE_DEBUG_MODE: "false"
          VITE_LOG_LEVEL: "error"
          VITE_ADMIN_EMAILS: ${{ vars.VITE_ADMIN_EMAILS }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name employees-map
